### PR TITLE
preperation for raylib-master fork

### PR DESCRIPTION
**Pull request by chriscamacho**
I'm making a fork for my own use, using python 3.9 and raylib-master, this PR was work done before any related work and should! work fine on your master branch...

### CODE REVIEW

**Comment by electronstudio** [comment]
there seem to be merge conflict makers in the final patch?

**Comment by chriscamacho** [comment]
dang, can you apply everything but that, I forgot subsequent git operations get added to this PR ...

if not close this PR, and I'll merge manually on a separate clean fork and do another PR (eventually...)

**Comment by electronstudio** [comment]
I have made a new PR with all the new example code (thank you!) but removed the raylib-master stuff https://github.com/electronstudio/raylib-python-cffi/pull/23

**Comment by electronstudio** [comment]
I have added your stuff for raylib master and python 3.9 (although i havent done the mac and windows builds yet) so I guess can close this now.

**Pull request closed without merging**
